name: 'Gatsby Stale Bot'
description: 'Action to close stale issues and PRs. Ignores issues that have assignees or specific exempt labels. Can also re-open issues after activity in the issue.'
author: 'gatsbyjs'
branding:
  icon: 'activity'
  color: 'purple'
inputs:
  GITHUB_TOKEN:
    description: 'Token for the repo'
    required: true
  DRY_RUN:
    description: 'Display the commands only to the console, no GitHub or Slack API requests to comment/close/mark will be made'
    default: false
  STALE_ISSUE_MESSAGE:
    description: 'The messsage to post when an issue is stale. If left empty, will not mark issues stale'
  CLOSE_MESSAGE:
    description: 'The message to post when an issue is closed'
  STALE_PR_MESSAGE:
    description: 'The messsage to post when a PR is stale. If left empty, will not mark PRs stale'
  DAYS_BEFORE_STALE:
    description: 'The number of days old an issue can be before marking it stale'
    required: true
    default: 20
  DAYS_BEFORE_CLOSE:
    description: 'The number of days to wait to close an issue or pull request after it being marked stale'
    required: true
    default: 10
  STALE_ISSUE_LABEL:
    description: 'The label to apply when an issue is stale (must already exist!)'
    required: true
    default: 'stale?'
  EXEMPT_ISSUE_LABELS:
    description: 'Issues with one or more labels defined here will be ignored by the bot'
  STALE_PR_LABEL:
    description: 'The label to apply when a PR is stale (must already exist!)'
    required: true
    default: 'stale?'
  EXEMPT_PR_LABELS:
    description: 'PRs with one or more labels defined here will be ignored by the bot'
  OPERATIONS_PER_RUN:
    description: 'The maximum number of operations per run, used to control rate limiting'
    required: true
    default: 30
outputs:
  blocks:
    description: 'Array of objects in the specific format that Slack API requires it, see: https://api.slack.com/tools/block-kit-builder'
  queue:
    description: 'Array of objects of the issues (URL and title) so that you can convert it into your own desired format'
runs:
  using: 'docker'
  image: 'Dockerfile'